const MIRROR_URL = './mirrors.json';
const state = { mirrorsData:null, results:[], checking:false, progress:{done:0,total:0,currentTool:'-',currentMirror:'-'}, filters:{ecosystem:'all',region:'all',status:'all',sort:'default'}, dockerIn:'', dockerOut:'' };
const byId=id=>document.getElementById(id);
const setHtml=(id,html)=>{const el=byId(id); if(el) el.innerHTML=html;};

function normalizeMirrorEntry(ecosystem, eco, mirror){return {ecosystem, ecosystemLabel:eco.label||ecosystem, icon:eco.icon, id:mirror.id||`${ecosystem}-${mirror.url}`, name:mirror.name||mirror.provider||mirror.url, url:mirror.url, country:mirror.country||'Unknown', countryCode:mirror.countryCode||'UNK', region:mirror.region||'Unknown', provider:mirror.provider||'Unknown', isOfficial:!!mirror.isOfficial, tags:mirror.tags||[], enabled:mirror.enabled!==false, test:mirror.test||{method:'GET',url:mirror.url}};}
function getMirrorDisplayName(m){ return `${m.name} (${m.provider})`; }
function getCountryBadge(m){ return `<span class='badge'>${m.countryCode}</span> <span class='text-slate-300'>${m.country}/${m.region}</span>`; }
function classifyCheckFailure(err,status){ if(err?.name==='AbortError') return 'timeout'; if(err?.message?.includes('Failed to fetch')) return 'network error / CORS blocked'; if(status && (status<200||status>=300)) return `non-2xx status (${status})`; return 'unknown error'; }
async function checkMirrorLatency(m){ const controller=new AbortController(); const t=setTimeout(()=>controller.abort(),7000); const start=performance.now(); try { const r=await fetch(m.test.url||m.url,{method:m.test.method||'GET',mode:'cors',signal:controller.signal,cache:'no-store'}); clearTimeout(t); const latency=Math.round(performance.now()-start); if(!r.ok) return {ok:false, latency, reason:classifyCheckFailure(null,r.status)}; return {ok:true,latency}; } catch(e){ clearTimeout(t); return {ok:false, latency:Math.round(performance.now()-start), reason:classifyCheckFailure(e)}; } }
function calculateSummaryStats(rows){ const success=rows.filter(r=>r.state==='success'); const failed=rows.filter(r=>r.state==='failed'); const fastest=success.slice().sort((a,b)=>a.latency-b.latency)[0]; const avg=success.length?Math.round(success.reduce((s,r)=>s+r.latency,0)/success.length):0; return {total:rows.length, checked:success.length+failed.length, success:success.length, failed:failed.length, fastest, average:avg}; }

function renderProgress(){ const p=state.progress; const percent=p.total?Math.round((p.done/p.total)*100):0; setHtml('actionsSection',`<div class='card'><div class='flex items-center gap-2'><button id='runCheck' ${state.checking?'disabled':''} class='btn-primary'>${state.checking?'Checking...':'Start check'}</button><span class='${state.checking?'spinner':''}' aria-hidden='true'></span><span class='text-sm'>${p.done}/${p.total} (${percent}%)</span></div><div class='progress mt-2'><div style='width:${percent}%'></div></div><p class='text-xs mt-2 text-slate-300'>Current: ${p.currentTool} → ${p.currentMirror}</p></div>`); byId('runCheck')?.addEventListener('click',runChecks); }
function renderFilters(){ const ecosystems=['all',...Object.keys(state.mirrorsData?.ecosystems||{})]; const regions=['all',...new Set(state.results.map(r=>r.countryCode))]; setHtml('categoryOverview',`<div class='card grid md:grid-cols-4 gap-2 text-xs'><select id='fEco'>${ecosystems.map(v=>`<option ${state.filters.ecosystem===v?'selected':''} value='${v}'>${v}</option>`)}</select><select id='fRegion'>${regions.map(v=>`<option ${state.filters.region===v?'selected':''} value='${v}'>${v}</option>`)}</select><select id='fStatus'><option value='all'>all</option><option value='success'>success</option><option value='failed'>failed</option></select><select id='fSort'><option value='default'>default</option><option value='latency'>latency</option><option value='country'>country</option><option value='ecosystem'>ecosystem</option><option value='provider'>provider</option></select></div>`); ['fEco','fRegion','fStatus','fSort'].forEach((id)=>byId(id).onchange=e=>{state.filters[{fEco:'ecosystem',fRegion:'region',fStatus:'status',fSort:'sort'}[id]]=e.target.value; renderResults(); renderLatencyChart();}); }
function getFiltered(){ let rows=[...state.results]; const f=state.filters; if(f.ecosystem!=='all') rows=rows.filter(r=>r.ecosystem===f.ecosystem); if(f.region!=='all') rows=rows.filter(r=>r.countryCode===f.region); if(f.status!=='all') rows=rows.filter(r=>r.state===f.status); if(f.sort==='latency') rows.sort((a,b)=>(a.state==='success'?0:1)-(b.state==='success'?0:1)||a.latency-b.latency); else if(f.sort==='country') rows.sort((a,b)=>a.countryCode.localeCompare(b.countryCode)); else if(f.sort==='ecosystem') rows.sort((a,b)=>a.ecosystem.localeCompare(b.ecosystem)); else if(f.sort==='provider') rows.sort((a,b)=>a.provider.localeCompare(b.provider)); else rows.sort((a,b)=>(a.state==='success'?0:1)-(b.state==='success'?0:1)||a.latency-b.latency); return rows; }
function renderResults(){ const rows=getFiltered(); const s=calculateSummaryStats(rows); setHtml('summary',`<div class='card text-xs'>Total ${s.total} · Checked ${s.checked} · Success ${s.success} · Failed ${s.failed} · Fastest ${s.fastest?getMirrorDisplayName(s.fastest)+' '+s.fastest.latency+'ms':'-'} · Avg ${s.average}ms</div>`); setHtml('latencySection',`<div class='grid gap-2'>${rows.map(r=>`<div class='card ${r.state==='success'?'ok':r.state==='failed'?'fail':'checking'} text-xs'><div class='flex justify-between gap-2'><div><img src='${r.icon}' alt='${r.ecosystemLabel}' title='${r.ecosystemLabel}' class='icon inline'> <strong>${r.ecosystemLabel}</strong> · ${getMirrorDisplayName(r)}<br>${getCountryBadge(r)}</div><div>${r.state==='success'?r.latency+'ms':r.state==='failed'?'failed: '+r.reason:'pending'}</div></div></div>`).join('')}</div>`); }
function renderLatencyChart(){ const rows=getFiltered(); const max=Math.max(...rows.filter(r=>r.state==='success').map(r=>r.latency),1); const bars=rows.map((r,i)=>`<g transform='translate(0,${i*20})'><text x='0' y='14' font-size='11' fill='#cbd5e1'>${r.countryCode} ${r.ecosystem}: ${r.provider}</text>${r.state==='success'?`<rect x='210' y='4' width='${Math.max(4,Math.round((r.latency/max)*220))}' height='10' fill='#22d3ee'/><text x='440' y='14' font-size='10' fill='#e2e8f0'>${r.latency}ms</text>`:`<text x='220' y='14' font-size='10' fill='#fda4af'>failed</text>`}</g>`).join(''); setHtml('envSection',`<div class='card'><h3 class='text-sm mb-2'>Latency chart</h3><svg viewBox='0 0 500 ${Math.max(50,rows.length*20+20)}' class='w-full'>${bars}</svg></div>`); }

async function runChecks(){ const items=Object.entries(state.mirrorsData.ecosystems).flatMap(([k,v])=>(v.mirrors||[]).map(m=>normalizeMirrorEntry(k,v,m)).filter(m=>m.enabled)); state.results=items.map(m=>({...m,state:'pending',latency:0,reason:''})); state.checking=true; state.progress={done:0,total:items.length,currentTool:'-',currentMirror:'-'}; render(); for(let i=0;i<state.results.length;i++){ const r=state.results[i]; r.state='checking'; state.progress.currentTool=r.ecosystemLabel; state.progress.currentMirror=r.name; renderProgress(); renderResults(); const res=await checkMirrorLatency(r); r.state=res.ok?'success':'failed'; r.latency=res.latency; r.reason=res.reason||''; state.progress.done=i+1; renderProgress(); renderResults(); } state.checking=false; render(); }

function renderDocker(){ const fastest=state.results.filter(r=>r.state==='success').slice().sort((a,b)=>a.latency-b.latency).slice(0,5); setHtml('dockerfileSection',`<div class='card text-xs'><p><strong>Step 1:</strong> Check mirrors → <strong>Step 2:</strong> Review fastest → <strong>Step 3:</strong> Paste/upload Dockerfile → <strong>Step 4:</strong> Download optimized</p><p class='mt-2'>Selected mirrors: ${fastest.length?fastest.map(f=>`${f.ecosystem}:${f.provider}`).join(', '):'none yet'}</p><textarea id='dockerIn' class='w-full mt-2 compact-scroll rounded bg-slate-900 p-2' placeholder='Paste Dockerfile'>${state.dockerIn}</textarea><div class='mt-2 flex gap-2'><button id='genDocker' class='btn-primary' ${fastest.length?'':'disabled'}>Generate optimized</button><button id='dlDocker' class='btn' ${state.dockerOut?'':'disabled'}>Download</button></div><pre class='compact-scroll mt-2 rounded bg-slate-900 p-2'>${state.dockerOut||'No generated output yet.'}</pre></div>`); byId('dockerIn').oninput=e=>state.dockerIn=e.target.value; byId('genDocker').onclick=()=>{ if(!fastest.length) return; state.dockerOut=`# mirrors selected\n${fastest.map(f=>`# ${f.ecosystem} ${f.url}`).join('\n')}\n`+state.dockerIn; renderDocker();}; byId('dlDocker').onclick=()=>{const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([state.dockerOut])); a.download='Dockerfile.optimized'; a.click();}; }

async function init(){ try{ const r=await fetch(MIRROR_URL,{cache:'no-store'}); if(!r.ok) throw new Error(`HTTP ${r.status}`); state.mirrorsData=await r.json(); byId('statusMessage').textContent='mirrors.json loaded automatically.'; } catch(e){ byId('statusMessage').innerHTML=`Failed to load mirrors.json from <code>${MIRROR_URL}</code>. Ensure <code>docs-site/mirrors.json</code> exists. You can still upload fallback.`; }
 render(); }
function render(){ renderProgress(); renderFilters(); renderResults(); renderLatencyChart(); renderDocker(); }
document.addEventListener('DOMContentLoaded',init);
